#!/bin/bash
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null
# Set the number of processes here:
#$ -pe mpi 6
# Change the name of the executable here:
mpirun ./hybrid_clustering > outputs/parallel/p6m2000.txt
